name: tvl
dependencies:
  - conda-forge::av=6.1.2
  - cudatoolkit=11.3
  - hypothesis=4.10.0
  - numpy=1.19.2
  - pillow=8.3.1
  - pip=21.2.2
  - python=3.6.13
  - pytest=4.4.2
  - pytest-mock=1.10.1
  - pytest-xdist=1.28.0
  - pytorch::pytorch=1.10.0
  - scikit-build=0.11.1
  - swig=4.0.2
  - twine=3.4.1
  - wheel=0.37.0
  - x264=1!152.20180717
  - pip:
    - opencv-python==4.5.4.60
